name: CI

on:
  push:
    branches: master
    paths-ignore:
    - 'README.md'
    - 'binder/*'
    - 'docs/*'
  pull_request:
    paths-ignore:
    - 'README.md'
    - 'binder/*'
    - 'docs/*'

jobs:
  build_and_push:
    strategy:
      matrix:
        image_base_name:
        - minimal
        - datascience

    name: ${{ matrix.image_base_name }}-notebook
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: ruby/setup-ruby@master
      with:
        ruby-version: "3.0"

    - name: Build images
      run: rake build/${{ matrix.image_base_name }}

    - name: Tag
      run: |
        tag=${GITHUB_SHA:0:12}
        docker tag rubydata/${{ matrix.image_base_name }}-notebook:latest rubydata/${{ matrix.image_base_name }}-notebook:${tag}

    - name: List images
      run: docker images --format '{{.Repository}}:{{.Tag}}\t{{.ID}}'

    - name: Login to DockerHub
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Push images to DockerHub
      if: github.ref == 'refs/heads/master'
      run: |
        docker images --format '{{.Repository}}:{{.Tag}}' | grep rubydata/${{ matrix.image_base_name }}-notebook | while read image_name; do
          echo "Pushing ${image_name}"
          docker push ${image_name}
        done
